openapi: 3.0.3
info:
  title: Orders API
  version: 0.1.0
  description: Generic Orders API for demonstration
servers:
  - url: https://api.example.com
paths:
  /orders:
    get:
      summary: List orders
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
  /orders/{id}:
    get:
      summary: Get order by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        total:
          type: number
        createdAt:
          type: string
          format: date-time
